mod lcp24_nums_game;
mod lcp30_magic_tower;
mod p100_same_tree;
mod p101_symmetric_tree;
mod p102_binary_tree_level_order_traversal;
mod p103_binary_tree_zigzag_level_order_traversal;
mod p104_maximum_depth_of_binary_tree;
mod p105_construct_binary_tree_from_preorder_and_inorder_traversal;
mod p106_construct_binary_tree_from_inorder_and_postorder_traversal;
mod p107_binary_tree_level_order_traversal_ii;
mod p108_convert_sorted_array_to_binary_search_tree;
mod p112_path_sum;
mod p114_flatten_binary_tree_to_linked_list;
mod p120_triangle;
mod p121_best_time_to_buy_and_sell_stock;
mod p122_best_time_to_buy_and_sell_stock_ii;
mod p123_best_time_to_buy_and_sell_stock_iii;
mod p124_binary_tree_maximum_path_sum;
mod p125_valid_palindrome;
mod p1261_find_elements_in_a_contaminated_binary_tree;
mod p1276_number_of_burgers_with_no_waste_of_ingredients;
mod p127_word_ladder;
mod p128_longest_consecutive_sequence;
mod p129_sum_root_to_leaf_numbers;
mod p130_surrounded_regions;
mod p134_gas_station;
mod p135_candy;
mod p136_single_number;
mod p137_single_number_ii;
mod p139_word_break;
mod p144_binary_tree_preorder_traversal;
mod p145_binary_tree_postorder_traversal;
mod p149_max_points_on_a_line;
mod p150_evaluate_reverse_polish_notation;
mod p151_reverse_words_in_a_string;
mod p153_find_minimum_in_rotated_sorted_array;
mod p155_min_stack;
mod p162_find_peak_element;
mod p167_two_sum_ii_input_array_is_sorted;
mod p1686_stone_game_vi;
mod p1690_stone_game_vii;
mod p1696_jump_game_vi;
mod p169_majority_element;
mod p172_factorial_trailing_zeroes;
mod p173_binary_search_tree_iterator;
mod p1793_maximum_score_of_a_good_subarray;
mod p17_letter_combinations_of_a_phone_number;
mod p188_best_time_to_buy_and_sell_stock_iv;
mod p189_rotate_array;
mod p190_reverse_bits;
mod p191_number_of_1_bits;
mod p1969_minimum_non_zero_product_of_the_array_elements;
mod p1976_number_of_ways_to_arrive_at_destination;
mod p198_house_robber;
mod p1997_first_day_where_you_have_been_in_all_the_rooms;
mod p199_binary_tree_right_side_view;
mod p1_two_sum;
mod p200_number_of_islands;
mod p201_bitwise_and_of_numbers_range;
mod p202_happy_number;
mod p205_isomorphic_strings;
mod p207_course_schedule;
mod p2085_count_common_words_with_one_occurrence;
mod p208_implement_trie_prefix_tree;
mod p209_minimum_size_subarray_sum;
mod p20_valid_parentheses;
mod p210_course_schedule_ii;
mod p211_design_add_and_search_words_data_structure;
mod p2129_capitalize_the_title;
mod p212_word_search_ii;
mod p215_kth_largest_element_in_an_array;
mod p2171_removing_minimum_number_of_magic_beans;
mod p2182_construct_string_with_repeat_limit;
mod p219_contains_duplicate_ii;
mod p21_merge_two_sorted_lists;
mod p221_maximal_square;
mod p222_count_complete_tree_nodes;
mod p224_basic_calculator;
mod p225_implement_stack_using_queues;
mod p226_invert_binary_tree;
mod p228_summary_ranges;
mod p22_generate_parentheses;
mod p230_kth_smallest_element_in_a_bst;
mod p2312_selling_pieces_of_wood;
mod p232_implement_queue_using_stacks;
mod p235_lowest_common_ancestor_of_a_binary_search_tree;
mod p2368_reachable_nodes_with_restrictions;
mod p2369_check_if_there_is_a_valid_partition_for_the_array;
mod p236_lowest_common_ancestor_of_a_binary_tree;
mod p2386_find_the_k_sum_of_an_array;
mod p238_product_of_array_except_self;
mod p242_valid_anagram;
mod p2476_closest_nodes_queries_in_a_binary_search_tree;
mod p2549_count_distinct_numbers_on_board;
mod p2575_find_the_divisibility_array_of_a_string;
mod p2580_count_ways_to_group_overlapping_ranges;
mod p2581_count_number_of_possible_root_nodes;
mod p2583_kth_largest_sum_in_a_binary_tree;
mod p2617_minimum_number_of_visited_cells_in_a_grid;
mod p2641_cousins_in_binary_tree_ii;
mod p2642_design_graph_with_shortest_path_calculator;
mod p2670_find_the_distinct_difference_array;
mod p2671_frequency_tracker;
mod p2673_make_costs_of_paths_equal_in_a_binary_tree;
mod p2684_maximum_number_of_moves_in_a_grid;
mod p2697_lexicographically_smallest_palindrome;
mod p26_remove_duplicates_from_sorted_array;
mod p2719_count_of_integers;
mod p2744_find_maximum_number_of_string_pairs;
mod p274_h_index;
mod p2765_longest_alternating_subarray;
mod p2788_split_strings_by_separator;
mod p2789_largest_element_in_an_array_after_merge_operations;
mod p27_remove_element;
mod p2808_minimum_seconds_to_equalize_a_circular_array;
mod p2809_minimum_time_to_make_array_sum_at_most_x;
mod p2828_check_if_a_string_is_an_acronym_of_words;
mod p2834_find_the_minimum_possible_sum_of_a_beautiful_array;
mod p2846_minimum_edge_weight_equilibrium_queries_in_a_tree;
mod p2859_sum_of_values_at_indices_with_k_set_bits;
mod p2861_maximum_number_of_alloys;
mod p2864_maximum_odd_binary_number;
mod p2865_beautiful_towers_i;
mod p2867_count_valid_paths_in_a_tree;
mod p289_game_of_life;
mod p28_find_the_index_of_the_first_occurrence_in_a_string;
mod p2908_minimum_sum_of_mountain_triplets_i;
mod p290_word_pattern;
mod p2917_find_the_k_or_of_an_array;
mod p292_nim_game;
mod p2952_minimum_number_of_coins_to_be_added;
mod p295_find_median_from_data_stream;
mod p299_bulls_and_cows;
mod p2_add_two_numbers;
mod p300_longest_increasing_subsequence;
mod p303_range_sum_query_immutable;
mod p30_substring_with_concatenation_of_all_words;
mod p310_minimum_height_trees;
mod p3117_minimum_sum_of_values_by_dividing_array;
mod p3137_minimum_number_of_operations_to_make_word_k_periodic;
mod p322_coin_change;
mod p331_verify_preorder_serialization_of_a_binary_tree;
mod p33_search_in_rotated_sorted_array;
mod p34_find_first_and_last_position_of_element_in_sorted_array;
mod p35_search_insert_position;
mod p365_water_and_jug_problem;
mod p36_valid_sudoku;
mod p373_find_k_pairs_with_smallest_sums;
mod p380_insert_delete_getrandom_o1;
mod p383_ransom_note;
mod p392_is_subsequence;
mod p399_evaluate_division;
mod p39_combination_sum;
mod p3_longest_substring_without_repeating_characters;
mod p410_split_array_largest_sum;
mod p42_trapping_rain_water;
mod p433_minimum_genetic_mutation;
mod p447_number_of_boomerangs;
mod p452_minimum_number_of_arrows_to_burst_balloons;
mod p45_jump_game_ii;
mod p46_permutations;
mod p48_rotate_image;
mod p49_group_anagrams;
mod p4_median_of_two_sorted_arrays;
mod p502_ipo;
mod p50_powx_n;
mod p514_freedom_trail;
mod p518_coin_change_ii;
mod p52_n_queens_ii;
mod p530_minimum_absolute_difference_in_bst;
mod p53_maximum_subarray;
mod p54_spiral_matrix;
mod p551_student_attendance_record_i;
mod p55_jump_game;
mod p56_merge_intervals;
mod p57_insert_interval;
mod p58_length_of_last_word;
mod p637_average_of_levels_in_binary_tree;
mod p63_unique_paths_ii;
mod p64_minimum_path_sum;
mod p66_plus_one;
mod p670_maximum_swap;
mod p67_add_binary;
mod p68_text_justification;
mod p69_sqrtx;
mod p6_zigzag_conversion;
mod p70_climbing_stairs;
mod p71_simplify_path;
mod p72_edit_distance;
mod p73_set_matrix_zeroes;
mod p743_network_delay_time;
mod p74_search_a_2d_matrix;
mod p76_minimum_window_substring;
mod p77_combinations;
mod p79_word_search;
mod p7_reverse_integer;
mod p80_remove_duplicates_from_sorted_array_ii;
mod p82_remove_duplicates_from_sorted_list_ii;
mod p83_remove_duplicates_from_sorted_list;
mod p889_construct_binary_tree_from_preorder_and_postorder_traversal;
mod p88_merge_sorted_array;
mod p909_snakes_and_ladders;
mod p912_sort_an_array;
mod p918_maximum_sum_circular_subarray;
mod p938_range_sum_of_bst;
mod p94_binary_tree_inorder_traversal;
mod p97_interleaving_string;
mod p987_vertical_order_traversal_of_a_binary_tree;
mod p98_validate_binary_search_tree;
mod p993_cousins_in_binary_tree;
mod p9_palindrome_number;

mod p1184_distance_between_bus_stops;
mod p1227_airplane_seat_assignment_probability;
mod p1436_destination_city;
mod p1450_number_of_students_doing_homework_at_a_given_time;
mod p1845_seat_reservation_manager;
mod p1870_minimum_speed_to_arrive_on_time;
mod p1884_egg_drop_with_2_eggs_and_n_floors;
mod p1928_minimum_cost_to_reach_destination_in_time;
mod p2024_maximize_the_confusion_of_an_exam;
mod p2073_time_needed_to_buy_tickets;
mod p2181_merge_nodes_in_between_zeros;
mod p2187_minimum_time_to_complete_trips;
mod p2207_maximize_number_of_subsequences_in_a_string;
mod p2286_booking_concert_tickets_in_groups;
mod p2306_naming_a_company;
mod p2332_the_latest_time_to_catch_a_bus;
mod p2374_node_with_highest_edge_score;
mod p2376_count_special_integers;
mod p2390_removing_stars_from_a_string;
mod p2398_maximum_number_of_robots_within_budget;
mod p2414_length_of_the_longest_alphabetical_continuous_substring;
mod p2516_take_k_of_each_character_from_left_and_right;
mod p2535_difference_between_element_sum_and_digit_sum_of_an_array;
mod p2552_count_increasing_quadruplets;
mod p2555_maximize_win_from_two_segments;
mod p2576_find_the_maximum_number_of_marked_indices;
mod p2708_maximum_strength_of_a_group;
mod p2848_points_that_intersect_with_cars;
mod p2860_happy_students;
mod p3007_maximum_number_that_sum_of_the_prices_is_less_than_or_equal_to_k;
mod p3127_make_a_square_with_the_same_color;
mod p3133_minimum_array_end;
mod p3134_find_the_median_of_the_uniqueness_array;
mod p3142_check_if_grid_satisfies_conditions;
mod p3144_minimum_substring_partition_of_equal_character_frequency;
mod p3145_find_products_of_elements_of_big_array;
mod p3146_permutation_difference_between_two_strings;
mod p3153_sum_of_digit_differences_of_all_pairs;
mod p3154_find_number_of_ways_to_reach_the_k_th_stair;
mod p3158_find_the_xor_of_numbers_which_appear_twice;
mod p3162_find_the_number_of_good_pairs_i;
mod p3164_find_the_number_of_good_pairs_ii;
mod p3171_find_subarray_with_bitwise_or_closest_to_k;
mod p3174_clear_digits;
mod p3175_find_the_first_player_to_win_k_games_in_a_row;
mod p3176_find_the_maximum_length_of_a_good_subsequence_i;
mod p3177_find_the_maximum_length_of_a_good_subsequence_ii;
mod p3184_count_pairs_that_form_a_complete_day_i;
mod p3185_count_pairs_that_form_a_complete_day_ii;
mod p3191_minimum_operations_to_make_binary_array_elements_equal_to_one_i;
mod p3192_minimum_operations_to_make_binary_array_elements_equal_to_one_ii;
mod p3193_count_the_number_of_inversions;
mod p3194_minimum_average_of_smallest_and_largest_elements;
mod p3200_maximum_height_of_a_triangle;
mod p552_student_attendance_record_ii;
mod p698_partition_to_k_equal_sum_subsets;
mod p815_bus_routes;
mod p871_minimum_number_of_refueling_stops;
mod p887_super_egg_drop;
mod p908_smallest_range_i;
mod p910_smallest_range_ii;
mod p977_squares_of_a_sorted_array;
mod p983_minimum_cost_for_tickets;
mod p997_find_the_town_judge;

mod p3180_maximum_total_reward_using_operations_i;

mod p3181_maximum_total_reward_using_operations_ii;

mod p684_redundant_connection;

mod p685_redundant_connection_ii;

mod p3211_generate_binary_strings_without_adjacent_zeros;

mod p3216_lexicographically_smallest_string_after_a_swap;

mod p3165_maximum_sum_of_subsequence_with_non_adjacent_elements;

mod p3259_maximum_energy_boost_from_two_drinks;

mod p3226_number_of_bit_changes_to_make_two_integers_equal;

mod p638_shopping_offers;

mod p633_sum_of_square_numbers;

mod p3222_find_the_winning_player_in_coin_game;

mod p3254_find_the_power_of_k_size_subarrays_i;

mod p3255_find_the_power_of_k_size_subarrays_ii;

mod p3235_check_if_the_rectangle_corner_is_reachable;

mod p3242_design_neighbor_sum_service;

mod p540_single_element_in_a_sorted_array;

mod p1547_minimum_cost_to_cut_a_stick;

mod p3258_count_substrings_that_satisfy_k_constraint_i;

mod p3261_count_substrings_that_satisfy_k_constraint_ii;

mod p3249_count_the_number_of_good_nodes;

mod p3239_minimum_number_of_flips_to_make_binary_grid_palindromic_i;

mod p3240_minimum_number_of_flips_to_make_binary_grid_palindromic_ii;

mod p825_friends_of_appropriate_ages;

mod p661_image_smoother;

mod p3243_shortest_distance_after_road_addition_queries_i;

mod p3244_shortest_distance_after_road_addition_queries_ii;

mod p3248_snake_in_matrix;

mod p3233_find_the_count_of_numbers_which_are_not_special;

mod p3238_find_the_number_of_winning_players;

mod p632_smallest_range_covering_elements_from_k_lists;

mod p3206_alternating_groups_i;

mod p3208_alternating_groups_ii;

mod p3250_find_the_count_of_monotonic_pairs_i;

mod p3232_find_if_digit_game_can_be_won;

mod p51_n_queens;

mod p3274_check_if_two_chessboard_squares_have_the_same_color;

mod p2056_number_of_valid_move_combinations_on_chessboard;

mod p3001_minimum_moves_to_capture_the_queen;

mod p999_available_captures_for_rook;

mod p688_knight_probability_in_chessboard;

mod p782_transform_to_chessboard;

mod p1812_determine_color_of_a_chessboard_square;

mod p935_knight_dialer;

mod p2717_semi_ordered_permutation;

mod p2931_maximum_spending_after_buying_items;

mod p3264_final_array_state_after_k_multiplication_operations_i;

mod p3266_final_array_state_after_k_multiplication_operations_ii;

mod p1338_reduce_array_size_to_the_half;

mod p1847_closest_room;

mod p3291_minimum_number_of_valid_strings_to_form_target_i;

mod p3292_minimum_number_of_valid_strings_to_form_target_ii;

mod p3285_find_indices_of_stable_mountains;

mod p3138_minimum_length_of_anagram_concatenation;
